### ISSUE TITLE
episode len error

### ISSUE THREAD

**Issue by CarlDegio** [siddhanthaldar/BAKU#6]
When I run baku on libero, I found in line 55 at eval.py, `self.expert_replay_loader.dataset._max_episode_len` is zero at initialization. So it makes line 96 at libero.py `observation["features"][: state.shape[0]] = state` occur an error about dimension because of `observation["features"] = np.zeros(self._max_state_dim)` create a zero dim numpy array.

full error:
```
evaluating env 0
Error executing job with overrides: ['agent=baku', 'suite=libero', 'dataloader=libero', 'suite/task=libero_10', 'suite.hidden_dim=256', 'bc_weight=/home/lzh/PycharmProjects/BAKU/weight/baku.pt']
Traceback (most recent call last):
  File "/home/lzh/PycharmProjects/BAKU/baku/eval.py", line 208, in main
    workspace.eval()
  File "/home/lzh/PycharmProjects/BAKU/baku/eval.py", line 107, in eval
    time_step = self.env[env_idx].reset()
  File "/home/lzh/PycharmProjects/BAKU/baku/suite/libero.py", line 327, in reset
    time_step = self._env.reset(**kwargs)
  File "/home/lzh/PycharmProjects/BAKU/baku/suite/libero.py", line 228, in reset
    time_step = self._env.reset(**kwargs)
  File "/home/lzh/PycharmProjects/BAKU/baku/suite/libero.py", line 159, in reset
    return self._env.reset(**kwargs)
  File "/home/lzh/PycharmProjects/BAKU/baku/suite/libero.py", line 293, in reset
    obs = self._env.reset(**kwargs)
  File "/home/lzh/PycharmProjects/BAKU/baku/suite/libero.py", line 98, in reset
    observation["features"][: state.shape[0]] = state
ValueError: could not broadcast input array from shape (47,) into shape (0,)
```

**Comment by siddhanthaldar** [comment]
Hi, 

Can you confirm if the `root_dir` variable in `baku/cfgs/config_eval.yaml` has been set to where you have stored the dataset?

**Comment by CarlDegio** [comment]
I got that. I didn't found config_eval.yaml but only found config.yaml. Thank you!

**Comment by siddhanthaldar** [comment]
The file is [here](https://github.com/siddhanthaldar/BAKU/blob/main/baku/cfgs/config_eval.yaml#L9). [This](https://github.com/siddhanthaldar/BAKU/blob/80bc41b43300f547bcbb3b7dd91e276b1dfa83b0/baku/cfgs/config_eval.yaml#L9) is the `root_dir` variable that you will need to modify.
