### ISSUE TITLE
AttributeError: module 'suite' has no attribute 'libero'

### ISSUE THREAD

**Issue by BrightMoonStar** [siddhanthaldar/BAKU#9]
When I run `python train.py agent=baku suite=libero dataloader=libero suite/task=libero_90 suite.hidden_dim=256`, there happens an error like the following . Thanks for your reply !
```
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/LIVING_ROOM_SCENE2_pick_up_the_butter_and_put_it_in_the_basket.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/KITCHEN_SCENE2_stack_the_middle_black_bowl_on_the_back_black_bowl.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/STUDY_SCENE4_pick_up_the_book_in_the_middle_and_place_it_on_the_cabinet_shelf.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/LIVING_ROOM_SCENE4_stack_the_right_bowl_on_the_left_bowl_and_place_them_in_the_tray.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/KITCHEN_SCENE6_put_the_yellow_and_white_mug_to_the_front_of_the_white_mug.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/KITCHEN_SCENE8_turn_off_the_stove.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/KITCHEN_SCENE10_put_the_butter_at_the_back_in_the_top_drawer_of_the_cabinet_and_close_it.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/STUDY_SCENE3_pick_up_the_book_and_place_it_in_the_left_compartment_of_the_caddy.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/KITCHEN_SCENE9_put_the_frying_pan_on_the_cabinet_shelf.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/KITCHEN_SCENE4_close_the_bottom_drawer_of_the_cabinet.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/LIVING_ROOM_SCENE3_pick_up_the_ketchup_and_put_it_in_the_tray.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/LIVING_ROOM_SCENE6_put_the_white_mug_on_the_plate.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/STUDY_SCENE2_pick_up_the_book_and_place_it_in_the_front_compartment_of_the_caddy.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/STUDY_SCENE1_pick_up_the_book_and_place_it_in_the_right_compartment_of_the_caddy.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/LIVING_ROOM_SCENE5_put_the_red_mug_on_the_right_plate.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/KITCHEN_SCENE9_put_the_white_bowl_on_top_of_the_cabinet.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/KITCHEN_SCENE9_turn_on_the_stove_and_put_the_frying_pan_on_it.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/LIVING_ROOM_SCENE2_pick_up_the_tomato_sauce_and_put_it_in_the_basket.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/KITCHEN_SCENE1_open_the_top_drawer_of_the_cabinet.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/LIVING_ROOM_SCENE3_pick_up_the_butter_and_put_it_in_the_tray.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/KITCHEN_SCENE7_put_the_white_bowl_to_the_right_of_the_plate.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/LIVING_ROOM_SCENE3_pick_up_the_cream_cheese_and_put_it_in_the_tray.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/KITCHEN_SCENE2_stack_the_black_bowl_at_the_front_on_the_black_bowl_in_the_middle.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/STUDY_SCENE3_pick_up_the_white_mug_and_place_it_to_the_right_of_the_caddy.pkl
Loading /home/bingxing2/gpuuser478/Do_Not_Delete_4/BAKU/expert_demos/libero/libero_90/KITCHEN_SCENE4_close_the_bottom_drawer_of_the_cabinet_and_open_the_top_drawer.pkl
/home/bingxing2/gpuuser478/.conda/envs/baku/lib/python3.9/site-packages/robosuite/macros.py:53: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  ROBOSUITE_DEFAULT_LOGGER.warn("No private macro file found!")
[robosuite WARNING] No private macro file found! (macros.py:53)
[2024-07-21 16:33:05,043][robosuite_logs][WARNING] - No private macro file found!
[robosuite WARNING] It is recommended to use a private macro file (macros.py:54)
[2024-07-21 16:33:05,043][robosuite_logs][WARNING] - It is recommended to use a private macro file
[robosuite WARNING] To setup, run: python /home/bingxing2/gpuuser478/.conda/envs/baku/lib/python3.9/site-packages/robosuite/scripts/setup_macros.py (macros.py:55)
[2024-07-21 16:33:05,043][robosuite_logs][WARNING] - To setup, run: python /home/bingxing2/gpuuser478/.conda/envs/baku/lib/python3.9/site-packages/robosuite/scripts/setup_macros.py
[2024-07-21 16:33:05,506][OpenGL.platform.ctypesloader][INFO] - Failed to load library ( 'libOpenGL.so.0' ): /lib64/libOpenGL.so.0: undefined symbol: _glapi_tls_Current
[2024-07-21 16:33:05,755][OpenGL.platform.ctypesloader][INFO] - Failed to load library ( 'libOpenGL.so.0' ): /lib64/libOpenGL.so.0: undefined symbol: _glapi_tls_Current
Traceback (most recent call last):
  File "/home/bingxing2/gpuuser478/.conda/envs/baku/lib/python3.9/site-packages/hydra/_internal/utils.py", line 639, in _locate
    obj = getattr(obj, part)
AttributeError: module 'suite' has no attribute 'libero'

During handling of the above exception, another exception occurred:

RuntimeError: CPU dispatcher tracer already initlized
Error executing job with overrides: ['agent=baku', 'suite=libero', 'dataloader=libero', 'suite/task=libero_90', 'suite.hidden_dim=256']
Error locating target 'suite.libero.make', see chained exception above.
full_key: suite.task_make_fn

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/bingxing2/gpuuser478/.conda/envs/baku/lib/python3.9/threading.py", line 980, in _bootstrap_inner
```

**Comment by siddhanthaldar** [comment]
Hi,

Could you set `HYDRA_FULL_ERROR=1` while running the script and share the complete stack trace?

**Comment by siddhanthaldar** [comment]
Closing issue due to inactivity. Feel free to open the issue again if the problem persists.
